package com.blockchain.koin

import org.koin.core.qualifier.StringQualifier
import org.koin.core.qualifier.named

val interestAccountFeatureFlag = StringQualifier("ff_interest_account")
val obFeatureFlag = StringQualifier("ff_ob")
val achDepositWithdrawFeatureFlag = StringQualifier("ff_ach_deposit_withdrawal")
val sddFeatureFlag = StringQualifier("ff_sdd")
val mwaFeatureFlag = StringQualifier("ff_modern_wallet_auth")
val ssoLoginFeatureFlag = StringQualifier("ff_single_signin")
val nabu = StringQualifier("nabu")
val status = StringQualifier("status")
val kotlinApiRetrofit = StringQualifier("kotlin-api")
val explorerRetrofit = StringQualifier("explorer")
val everypayRetrofit = StringQualifier("everypay")
val apiRetrofit = StringQualifier("api")
val moshiExplorerRetrofit = StringQualifier("moshi_explorer")
val gbp = StringQualifier("GBP")
val usd = StringQualifier("USD")
val eur = StringQualifier("EUR")
val priorityFee = StringQualifier("Priority")
val regularFee = StringQualifier("Regular")
val bigDecimal = StringQualifier("BigDecimal")
val bigInteger = StringQualifier("BigInteger")
val interestLimits = StringQualifier("InterestLimits")
val interestEligibility = StringQualifier("InterestEligibility")
val kyc = StringQualifier("kyc")
val uniqueId = StringQualifier("unique_id")
val uniqueUserAnalytics = StringQualifier("unique_user_analytics")
val userAnalytics = StringQualifier("user_analytics")
val walletAnalytics = StringQualifier("wallet_analytics")
val payloadScopeQualifier = named("Payload")
