opt_out_usage

default_platform :android
platform :android do

    desc "Builds using the given environment and build type"
    lane :build do | options |

      environment = options[:environment]

      build_type = options[:build_type]

      gradle(
        task: 'assemble',
        build_type: build_type,
        flavor: 'Env' + environment,
        print_command: false
      )

    end

    desc "Runs all tests"
    lane :test do
      gradle(
        task: "coveralls"
        )
    end

    desc "Submit a release Alpha build to the Play Store. This won't publish, just upload."
    lane :alpha do

      upload_to_play_store(
          track: 'alpha',
          validate_only: 'true',
      )

    end

    desc "Upload to AppCenter."
    lane :upload_to_appcenter do
      #  Expected env vars: 
      #  APPCENTER_API_TOKEN, APPCENTER_DISTRIBUTE_FILE, APPCENTER_OWNER_NAME,
      #  APPCENTER_DISTRIBUTE_DESTINATIONS, APPCENTER_DISTRIBUTE_RELEASE_NOTES and APPCENTER_APP_NAME
      appcenter_upload
    end


    desc "Tests to run on CI"
    lane :ci_test do
      gradle(
        task: "coveralls",
        flags: "-Dpre-dex=false -Pkotlin.incremental=false --stacktrace --no-daemon --max-workers 2"
        )
    end

    desc "Build to run on CI"
    lane :ci_build do | options |

      environment = options[:environment]

      build_type = options[:build_type]

      sh("echo $FIREBASE_API_JSON_PROD > ../app/src/env/prod/google-services.json")
      sh("echo $FIREBASE_API_JSON_DEV > ../app/src/env/dev/google-services.json")
      sh("echo $FIREBASE_API_JSON_STAGING > ../app/src/env/staging/google-services.json")
      sh("echo $FIREBASE_API_JSON_TESTNET > ../app/src/env/testnet/google-services.json")

      sh("wget -O \"../app/secrets.properties\" \"$BITRISEIO_secrets_properties_URL\"")

      sh("echo \"file downloaded to: ../app/secrets.properties\"")

      gradle(
        task: 'assemble',
        build_type: build_type,
        flavor: 'Env' + environment,
        print_command: false,
        flags: "--info --stacktrace --no-daemon"
      )
    end

    desc "Checks to run on CI"
    lane :ci_lint do

      gradle(
        task: 'lint',
        build_type: 'Debug',
        flavor: 'EnvProd',
        print_command: false,
        flags: "lintDebug ktlint -Dpre-dex=false -Pkotlin.incremental=false --no-daemon --stacktrace"
      )
    end

    private_lane :ship_it do
      rand = Random.rand(0..1)
      if rand == 0
        squirrel
      elsif rand == 1
        boat
      end
    end
    

    def squirrel
      puts "
        !!!!
      !!!!!!!!
    !!!!!!!!!!!   O_O
    !!!  !!!!!!! /@ @\\
          !!!!!! \\ x /
          !!!!!!/ m  !m
           !!!!/ __  |
           !!!!|/  \\__
            !!!\\______\\
      "
    end

    def boat
      puts "
         .  o ..
         o . o o.o
              ...oo
                __[]__
             __|_o_o_o\__
             \\\"\"\"\"\"\"\"\"\"\"/
              \\. ..  . /
         ^^^^^^^^^^^^^^^^^^^^
      "
    end


    after_all do |lane|
      # This block is called, only if the executed lane was successful
      ship_it
    end


    error do |lane, exception|
      # This block is called, only if the executed lane failed with an exception
    end
    
end
